package u02_x08_iniciosesion;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 * @author Aser <agranadoa09@iesvjp.es>
 */
public class InicioSesion extends javax.swing.JFrame {
    //? CONSTANTES
    private static final String FICHERO_USUARIOS = "./users.txt";
//    private static final char[] CARACTERES_BANEADOS = { '=' };
    //? Variables ESTATICAS
    private static Properties usuarios;
    private static Properties getUsuarios() {
        if (usuarios == null) {
            usuarios = new Properties(); FileInputStream fis = null;
            try {
                fis = new FileInputStream(Utils.getFile(FICHERO_USUARIOS));
                usuarios.load(fis);
            } catch (IOException e) { e.printStackTrace(); 
            } finally { Utils.cerrarStream(fis); }
        } return usuarios;
    }
    private static void guardarFicheroUsuarios() {
        if (usuarios != null) { 
            FileOutputStream fos = null;
            try {
                fos = new FileOutputStream(Utils.getFile(FICHERO_USUARIOS));
                usuarios.store(fos, null);
            } catch (IOException e) { e.printStackTrace(); 
            } finally { Utils.cerrarStream(fos); }
        }
    }
    
    private static boolean validarUsuario(String user, String pass) {
        String validPass = getUsuarios().getProperty(user);
        return pass.equals(validPass);
    }
    private static void registrarUsuario(String user, String pass) {
        if (getUsuarios().getProperty(user) == null) {
            getUsuarios().setProperty(user, pass);
            guardarFicheroUsuarios();
        }
    }
    
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        // Añadir normas de validación
        // Usuario
        ValidationGroup validation = validationPanel.getValidationGroup();
        validation.add(field_user, StringValidators.REQUIRE_NON_EMPTY_STRING);
//        validation.add(field_user, StringValidators.disallowChars(CARACTERES_BANEADOS));
        validation.add(field_user, StringValidators.NO_WHITESPACE);
        // Constraseña
        validation.add(passwordField_pass, StringValidators.REQUIRE_NON_EMPTY_STRING);
//        validation.add(passwordField_pass, StringValidators.disallowChars(CARACTERES_BANEADOS));
        validation.add(passwordField_pass, StringValidators.NO_WHITESPACE);
        
        // Deshabilitar botones si no valida
        validationPanel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanel.getProblem() == null) {
                    button_login.setEnabled(true);
                    button_register.setEnabled(true);
                } else {
                    button_login.setEnabled(false);
                    button_register.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel();
        panel_fondo_login = new javax.swing.JPanel();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        label_user = new javax.swing.JLabel();
        field_user = new javax.swing.JTextField();
        label_pass = new javax.swing.JLabel();
        passwordField_pass = new javax.swing.JPasswordField();
        button_register = new javax.swing.JButton();
        button_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_fondo.setBackground(new java.awt.Color(100, 0, 200));

        panel_fondo_login.setBackground(new java.awt.Color(51, 51, 51));

        validationPanel.setBackground(new java.awt.Color(51, 51, 51));
        validationPanel.setForeground(new java.awt.Color(255, 255, 255));

        label_user.setBackground(new java.awt.Color(255, 255, 255));
        label_user.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_user.setForeground(new java.awt.Color(255, 255, 255));
        label_user.setText(org.openide.util.NbBundle.getMessage(InicioSesion.class, "InicioSesion.label_user.text")); // NOI18N

        field_user.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        field_user.setText(org.openide.util.NbBundle.getMessage(InicioSesion.class, "InicioSesion.Usuario.text")); // NOI18N
        field_user.setName("Usuario"); // NOI18N

        label_pass.setBackground(new java.awt.Color(255, 255, 255));
        label_pass.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_pass.setForeground(new java.awt.Color(255, 255, 255));
        label_pass.setText(org.openide.util.NbBundle.getMessage(InicioSesion.class, "InicioSesion.label_pass.text")); // NOI18N

        passwordField_pass.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        passwordField_pass.setText(org.openide.util.NbBundle.getMessage(InicioSesion.class, "InicioSesion.Constraseña.text")); // NOI18N
        passwordField_pass.setName("Constraseña"); // NOI18N

        button_register.setText(org.openide.util.NbBundle.getMessage(InicioSesion.class, "InicioSesion.button_register.text")); // NOI18N
        button_register.setEnabled(false);
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        button_login.setText(org.openide.util.NbBundle.getMessage(InicioSesion.class, "InicioSesion.button_login.text")); // NOI18N
        button_login.setEnabled(false);
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fondo_loginLayout = new javax.swing.GroupLayout(panel_fondo_login);
        panel_fondo_login.setLayout(panel_fondo_loginLayout);
        panel_fondo_loginLayout.setHorizontalGroup(
            panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondo_loginLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_fondo_loginLayout.createSequentialGroup()
                        .addComponent(validationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_register)
                        .addGap(6, 6, 6)
                        .addComponent(button_login))
                    .addGroup(panel_fondo_loginLayout.createSequentialGroup()
                        .addGroup(panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField_pass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(field_user, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(15, 15, 15))
        );
        panel_fondo_loginLayout.setVerticalGroup(
            panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_fondo_loginLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(field_user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_user, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_fondo_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout panel_fondoLayout = new javax.swing.GroupLayout(panel_fondo);
        panel_fondo.setLayout(panel_fondoLayout);
        panel_fondoLayout.setHorizontalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_fondo_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        panel_fondoLayout.setVerticalGroup(
            panel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fondoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panel_fondo_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        String user = field_user.getText(),
               pass = String.copyValueOf(passwordField_pass.getPassword());
        registrarUsuario(user, pass);
    }//GEN-LAST:event_button_registerActionPerformed

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        String user = field_user.getText(),
               pass = String.copyValueOf(passwordField_pass.getPassword());
        if (validarUsuario(user, pass)) {
            System.out.println("Sesión Iniciada");
        } else {
            System.out.println("Usuario/Contraseña inválidos");
        }
    }//GEN-LAST:event_button_loginActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JButton button_register;
    private javax.swing.JTextField field_user;
    private javax.swing.JLabel label_pass;
    private javax.swing.JLabel label_user;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JPanel panel_fondo_login;
    private javax.swing.JPasswordField passwordField_pass;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
}
